package com.prapps.hello.client.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-05-07T09:39:23.404+05:30
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://ejb.hello.prapps.com/", name = "Hello")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Hello {

    @WebResult(name = "sayHelloRemoteDetailResponse", targetNamespace = "http://ejb.hello.prapps.com/", partName = "sayHelloRemoteDetailResponse")
    @WebMethod
    public HelloResponse sayHelloRemoteDetail(
        @WebParam(partName = "sayHelloRemoteDetail", name = "sayHelloRemoteDetail", targetNamespace = "http://ejb.hello.prapps.com/")
        HelloRequest sayHelloRemoteDetail
    );

    @WebResult(name = "sayHelloRemoteResponse", targetNamespace = "http://ejb.hello.prapps.com/", partName = "sayHelloRemoteResponse")
    @WebMethod
    public java.lang.String sayHelloRemote();
}
