package com.tict.project.feedback.consts;

public interface FeedbackConsts {

	public static final String SCHEMA = "FEEDBACK";
	public static final String ROLE_ADMIN = "ADMIN";
	public static final String ROLE_FACULTY = "FACULTY";
	public static final String ROLE_STUDENT = "STUDENT";
	
	
	public static final String ERROR_MSG = "errorMsg";
	public static final String MSG = "msg";
	public static final String LOGIN_PAGE = "Login.jsp";
	public static final String ERROR_PAGE = "Error.jsp";
	
	
	//QUERIES
	public static final String QUERY_STUDENT_SUBJECTS_FACULTY = "SELECT T2.SUBJECT_ID, T2.FACULTY_ID ,T3.NAME AS SUBJECT_NAME, T4.ID AS FACULTY_ID, T4.FNAME, T4.LNAME, T2.ID AS SEM_SUB_FAC_ID, T6.ID AS COURSE_ID, T6.NAME AS COURSE_NAME"
			+ " FROM "+SCHEMA+".STUDENT_SEM_ENROLL T1, "+SCHEMA+".SEMESTER_SUBJECT_FACULTY T2, "+SCHEMA+".SUBJECT T3, "+SCHEMA+".USER T4, "+SCHEMA+".SEMESTER T5,"+SCHEMA+".COURSE T6"
			+ " WHERE T1.SEMESTER_ID=T2.SEMESTER_ID AND T3.ID=T2.SUBJECT_ID AND T4.ID=T2.FACULTY_ID "
			+ " AND T2.ID NOT IN (SELECT SEM_SUB_FAC_ID FROM "+SCHEMA+".FEEDBACK WHERE STUDENT_ID=?)"
			+ " AND T5.ID=T1.SEMESTER_ID AND T5.COURSE_ID=T6.ID AND T4.UTYPE='FACULTY'"
			+ " AND T1.SEMESTER_ID=T2.SEMESTER_ID AND T1.STUDENT_ID=?";
	
	public static final String QUERY_INSERT_FEEDBACK = "INSERT INTO "+SCHEMA+".FEEDBACK(EVALUATION, FEEDBACK_CONFIG_ID, STUDENT_ID, SEM_SUB_FAC_ID) "
			+ "VALUES(?, ?, ?, ?)"; 
	
	public static final String QUERY_VIEW_FEEDBACK = "SELECT USER.FNAME, FC.ATTRIBUTE_DESC , AVG(F.EVALUATION), USER.ID, SSF.ID ,FC.ID"
			+ " FROM "+SCHEMA+".USER USER, "+SCHEMA+".SEMESTER_SUBJECT_FACULTY SSF, "+SCHEMA+".FEEDBACK F, "+SCHEMA+".FEEDBACK_CONFIG FC"
			+ " GROUP BY USER.FNAME, USER.UTYPE, SSF.FACULTY_ID, USER.ID, F.SEM_SUB_FAC_ID, SSF.ID, FC.ATTRIBUTE_DESC, F.FEEDBACK_CONFIG_ID, FC.ID"
			+ " HAVING UTYPE='FACULTY' AND USER.ID=SSF.FACULTY_ID AND F.SEM_SUB_FAC_ID=SSF.ID AND F.FEEDBACK_CONFIG_ID=FC.ID;";
}
