
package com.prapps.tutorial.webservice.jaxws.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.prapps.tutorial.webservice.jaxws.api.Employee;
import com.prapps.tutorial.webservice.jaxws.api.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeService", targetNamespace = "http://api.jaxws.webservice.tutorial.prapps.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.prapps.tutorial.webservice.jaxws.api.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findPerson", targetNamespace = "http://api.jaxws.webservice.tutorial.prapps.com/", className = "com.prapps.tutorial.webservice.jaxws.api.FindPerson")
    @ResponseWrapper(localName = "findPersonResponse", targetNamespace = "http://api.jaxws.webservice.tutorial.prapps.com/", className = "com.prapps.tutorial.webservice.jaxws.api.FindPersonResponse")
    @Action(input = "http://api.jaxws.webservice.tutorial.prapps.com/EmployeeService/findPersonRequest", output = "http://api.jaxws.webservice.tutorial.prapps.com/EmployeeService/findPersonResponse")
    public Employee findPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

}
