DROP SCHEMA FEEDBACK IF EXISTS;
CREATE SCHEMA FEEDBACK;
set schema FEEDBACK;

CREATE TABLE USER(
ID NUMBER(10) PRIMARY KEY auto_increment,
UNAME VARCHAR2(255) UNIQUE,
PASSWORD VARCHAR2(255),
FNAME VARCHAR2(255),
LNAME VARCHAR2(255),
UTYPE VARCHAR2(25)
); 


CREATE TABLE COURSE(
ID NUMBER(10) PRIMARY KEY,
NAME VARCHAR2(255) NOT NULL,
);


CREATE TABLE SUBJECT(
ID NUMBER(10) PRIMARY KEY,
NAME VARCHAR2(255) NOT NULL,
);


CREATE TABLE FEEDBACK_CONFIG(
ID NUMBER(10) PRIMARY KEY,
ATTRIBUTE VARCHAR2(255) NOT NULL,
ATTRIBUTE_DESC VARCHAR2(255) NOT NULL
);




CREATE TABLE STUDENT_COURSE_ENROLL(
ID NUMBER(10) PRIMARY KEY auto_increment,
STUDENT_ID NUMBER(10),
COURSE_ID NUMBER(10),
FOREIGN KEY (STUDENT_ID) REFERENCES USER(ID),
FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID)
);



CREATE TABLE FAC_SUB_COURSE_XREF(
ID NUMBER(10) PRIMARY KEY,
SUBJECT_ID NUMBER(10),
COURSE_ID NUMBER(10),
FACULTY_ID NUMBER(10),
FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECT(ID),
FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID),
FOREIGN KEY (FACULTY_ID) REFERENCES USER(ID)
);

CREATE TABLE FEEDBACK(
ID NUMBER(10) PRIMARY KEY,
FEEDBACK_CONFIG_ID NUMBER(10) NOT NULL,
STUDENT_ID NUMBER(10),
FAC_SUB_COURSE_ID NUMBER(10),
FOREIGN KEY (FEEDBACK_CONFIG_ID) REFERENCES FEEDBACK_CONFIG(ID),
FOREIGN KEY (STUDENT_ID) REFERENCES USER(ID),
FOREIGN KEY (FAC_SUB_COURSE_ID) REFERENCES FAC_SUB_COURSE_XREF(ID),
EVALUATION VARCHAR2(20)
);

