DROP SCHEMA FEEDBACK IF EXISTS;
CREATE SCHEMA FEEDBACK;
set schema FEEDBACK;

CREATE TABLE USER(
ID NUMBER(10) PRIMARY KEY auto_increment,
UNAME VARCHAR2(255) UNIQUE,
PASSWORD VARCHAR2(255),
FNAME VARCHAR2(255),
LNAME VARCHAR2(255),
UTYPE VARCHAR2(25)
); 


CREATE TABLE COURSE(
ID NUMBER(10) PRIMARY KEY auto_increment,
NAME VARCHAR2(255) NOT NULL,
);


CREATE TABLE SUBJECT(
ID NUMBER(10) PRIMARY KEY auto_increment,
NAME VARCHAR2(255) NOT NULL,
);


CREATE TABLE FEEDBACK_CONFIG(
ID NUMBER(10) PRIMARY KEY,
ATTRIBUTE VARCHAR2(255) NOT NULL,
ATTRIBUTE_DESC VARCHAR2(255) NOT NULL
);




CREATE TABLE STUDENT_COURSE_ENROLL(
ID NUMBER(10) PRIMARY KEY auto_increment,
STUDENT_ID NUMBER(10),
COURSE_ID NUMBER(10),
FOREIGN KEY (STUDENT_ID) REFERENCES USER(ID),
FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID)
);



CREATE TABLE FAC_SUB_COURSE_XREF(
ID NUMBER(10) PRIMARY KEY auto_increment,
SUBJECT_ID NUMBER(10),
COURSE_ID NUMBER(10),
FACULTY_ID NUMBER(10),
FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECT(ID),
FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID),
FOREIGN KEY (FACULTY_ID) REFERENCES USER(ID)
);


CREATE TABLE FEEDBACK(
ID NUMBER(10) PRIMARY KEY auto_increment,
FEEDBACK_CONFIG_ID NUMBER(10) NOT NULL,
STUDENT_ID NUMBER(10),
FAC_SUB_COURSE_ID NUMBER(10),
FOREIGN KEY (FEEDBACK_CONFIG_ID) REFERENCES FEEDBACK_CONFIG(ID),
FOREIGN KEY (STUDENT_ID) REFERENCES USER(ID),
FOREIGN KEY (FAC_SUB_COURSE_ID) REFERENCES FAC_SUB_COURSE_XREF(ID),
EVALUATION NUMBER(2,2)
);












INSERT INTO USER VALUES(101,'GARGI','PASSWORD','GARGI','MUKHERJEE','STUDENT');
INSERT INTO USER VALUES(102,'SAGAR','PASSWORD','SAGAR','MUKHERJEE','STUDENT');
INSERT INTO USER VALUES(501,'ANKITA','PASSWORD','ANKITA', 'GANGULY', 'ADMIN');
INSERT INTO USER VALUES(801,'BARSHA','PASSWORD','Barsha','Mukherjee','FACULTY');
INSERT INTO USER VALUES(802,'mpathak','PASSWORD','Manoj','Pathak','FACULTY');


INSERT INTO COURSE(NAME) VALUES('MCA');
INSERT INTO COURSE(NAME) VALUES('BCA');



INSERT INTO SUBJECT(NAME) VALUES('JAVA');
INSERT INTO SUBJECT(NAME) VALUES('C');
INSERT INTO SUBJECT(NAME) VALUES('ISAD');
INSERT INTO SUBJECT(NAME) VALUES('UNIX');
INSERT INTO SUBJECT(NAME) VALUES('C++');
INSERT INTO SUBJECT(NAME) VALUES('Maths');
INSERT INTO SUBJECT(NAME) VALUES('DBMS');



delete from FEEDBACK_CONFIG;
INSERT INTO FEEDBACK_CONFIG(ID, ATTRIBUTE, ATTRIBUTE_DESC)  VALUES(1,'DEPTH','DEPTH_IN_SUBJECT');
INSERT INTO FEEDBACK_CONFIG(ID, ATTRIBUTE, ATTRIBUTE_DESC)  VALUES(2,'COMM_SKILL','COMMUNICATION_SKILL');
INSERT INTO FEEDBACK_CONFIG(ID, ATTRIBUTE, ATTRIBUTE_DESC)  VALUES(3,'RELATION','RELATIONSHIP_WITH_STUDENT');
INSERT INTO FEEDBACK_CONFIG(ID, ATTRIBUTE, ATTRIBUTE_DESC)  VALUES(4,'CONFIDENCE','CONFIDENCE_IN_TEACHING');
INSERT INTO FEEDBACK_CONFIG(ID, ATTRIBUTE, ATTRIBUTE_DESC)  VALUES(5,'PATIENCE','PATIENCE');
INSERT INTO FEEDBACK_CONFIG(ID, ATTRIBUTE, ATTRIBUTE_DESC)  VALUES(6,'COMFORT','HOW FREE YOU FEEL TO ASK A QUESTION?');
INSERT INTO FEEDBACK_CONFIG(ID, ATTRIBUTE, ATTRIBUTE_DESC)  VALUES(7,'PUNCTUALITY','HOW PUNCTUAL THE TEACHER IS');
INSERT INTO FEEDBACK_CONFIG(ID, ATTRIBUTE, ATTRIBUTE_DESC)  VALUES(8,'INTEREST','HOW INTERSTING THE CLASS IS');
INSERT INTO FEEDBACK_CONFIG(ID, ATTRIBUTE, ATTRIBUTE_DESC)  VALUES(9,'NOTES','HOW RELEVANT IS THAT NOTES TO STUDY');


INSERT INTO STUDENT_COURSE_ENROLL(STUDENT_ID, COURSE_ID) VALUES(101,1);
INSERT INTO STUDENT_COURSE_ENROLL(STUDENT_ID, COURSE_ID) VALUES(102,2);



INSERT INTO FAC_SUB_COURSE_XREF(SUBJECT_ID, COURSE_ID, FACULTY_ID) VALUES(2,2,801);
--INSERT INTO FEEDBACK VALUES(501,1,123,401,'GOOD');