set schema feedback;
delete from USER;
INSERT INTO USER VALUES(101,'GARGI','PASSWORD','GARGI','MUKHERJEE','STUDENT');
INSERT INTO USER VALUES(102,'SAGAR','PASSWORD','SAGAR','MUKHERJEE','STUDENT');
INSERT INTO USER VALUES(501,'ANKITA','PASSWORD','ANKITA', 'GANGULY', 'ADMIN');
INSERT INTO USER VALUES(801,'BARSHA','PASSWORD','Barsha','Mukherjee','FACULTY');
INSERT INTO USER VALUES(802,'mpathak','PASSWORD','Manoj','Pathak','FACULTY');


INSERT INTO COURSE(NAME) VALUES('MCA');
INSERT INTO COURSE(NAME) VALUES('BCA');



INSERT INTO SUBJECT(NAME) VALUES('JAVA');
INSERT INTO SUBJECT(NAME) VALUES('C');
INSERT INTO SUBJECT(NAME) VALUES('ISAD');
INSERT INTO SUBJECT(NAME) VALUES('UNIX');
INSERT INTO SUBJECT(NAME) VALUES('C++');
INSERT INTO SUBJECT(NAME) VALUES('Maths');
INSERT INTO SUBJECT(NAME) VALUES('DBMS');



delete from FEEDBACK_CONFIG;
INSERT INTO FEEDBACK_CONFIG(ID, ATTRIBUTE, ATTRIBUTE_DESC)  VALUES(1,'DEPTH','DEPTH_IN_SUBJECT');
INSERT INTO FEEDBACK_CONFIG(ID, ATTRIBUTE, ATTRIBUTE_DESC)  VALUES(2,'COMM_SKILL','COMMUNICATION_SKILL');
INSERT INTO FEEDBACK_CONFIG(ID, ATTRIBUTE, ATTRIBUTE_DESC)  VALUES(3,'RELATION','RELATIONSHIP_WITH_STUDENT');
INSERT INTO FEEDBACK_CONFIG(ID, ATTRIBUTE, ATTRIBUTE_DESC)  VALUES(4,'CONFIDENCE','CONFIDENCE_IN_TEACHING');
INSERT INTO FEEDBACK_CONFIG(ID, ATTRIBUTE, ATTRIBUTE_DESC)  VALUES(5,'PATIENCE','PATIENCE');
INSERT INTO FEEDBACK_CONFIG(ID, ATTRIBUTE, ATTRIBUTE_DESC)  VALUES(6,'COMFORT','HOW FREE YOU FEEL TO ASK A QUESTION?');
INSERT INTO FEEDBACK_CONFIG(ID, ATTRIBUTE, ATTRIBUTE_DESC)  VALUES(7,'PUNCTUALITY','HOW PUNCTUAL THE TEACHER IS');
INSERT INTO FEEDBACK_CONFIG(ID, ATTRIBUTE, ATTRIBUTE_DESC)  VALUES(8,'INTEREST','HOW INTERSTING THE CLASS IS');
INSERT INTO FEEDBACK_CONFIG(ID, ATTRIBUTE, ATTRIBUTE_DESC)  VALUES(9,'NOTES','HOW RELEVANT IS THAT NOTES TO STUDY');


INSERT INTO STUDENT_COURSE_ENROLL(STUDENT_ID, COURSE_ID) VALUES(101,1);
INSERT INTO STUDENT_COURSE_ENROLL(STUDENT_ID, COURSE_ID) VALUES(102,2);



INSERT INTO FAC_SUB_COURSE_XREF(SUBJECT_ID, COURSE_ID, FACULTY_ID) VALUES(2,2,801);
INSERT INTO FEEDBACK VALUES(501,1,123,401,'GOOD');